name: Native CI

on: push

jobs:

  verify:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Info
        run: mvn -version
      - name: Start Database
        run: ./docker/start_db.sh
      - name: verify
        run: mvn verify -Pnative
